# Generated by Django 4.2.6 on 2023-10-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieReview',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
