# Generated by Django 4.2.6 on 2023-10-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_geeksmodel_alter_director_director_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
